# This is a basic workflow to auto-create a PR on push

name: pre-commit

# Controls when the workflow will run
on:
  # Triggers the workflow on push to any branch
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Pre-commit"
  pre-commit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
      - name: re-commit
        if: steps.pre-commit.outputs.exit-code == 1
        runs: |
          git commit -am "automated changes added"
          git push
